# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroupTalk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GroupTalk
pod 'SnapKit', '~> 4.0.0'

  target 'GroupTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GroupTalkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Core'
pod 'Firebase/RemoteConfig'
pod 'TextFieldEffects'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

end
