# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkExam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkExam

  target 'NetworkExamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetworkExamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Alamofire', '~> 5.0.0-beta.2'


end
