# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageLocalDownload' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageLocalDownload

  target 'ImageLocalDownloadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageLocalDownloadUITests' do
    # Pods for testing
  end

  pod 'Kingfisher'

end
