# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NSCacheKingfisherExam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NSCacheKingfisherExam

  target 'NSCacheKingfisherExamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NSCacheKingfisherExamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Kingfisher'

end
