# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DAOPatternExam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DAOPatternExam

  target 'DAOPatternExamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DAOPatternExamUITests' do
    inherit! :search_paths
    # Pods for testing
  end
# pod 'FMDB/FTS'   # FMDB with FTS
    # pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
    # pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
    # pod 'FMDB/SQLCipher'   # FMDB with SQLCipher

end
